version: "3"

services:
  db:
    image: mongo # container image to be used
    restart: always 
    ports: # expose ports in “host:container” format
      - 27017:27017
    environment: #env variables to pass into the container
       MONGODB_DATABASE: nest_rest_api

# Starting containers (in detached/background mode)
# docker-compose up -d

# Taking containers down
# docker-compose down